on: push
env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  JAVA_VERSION: 17
  AZURE_SUBSCRIPTION: 0917b8b7-c85b-4a76-9d2d-aed90d7d3b99
  SERVICE_NAME: api-movienchill
  APP-NAME: userservice
  ENV_DEV: false

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to production with artifact
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v2
        
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: maven build, clean
        run: |
          mvn clean package -DskipTests
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy to production with artifact
        uses: azure/spring-cloud-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: Deploy
          service-name: ${{ env.SERVICE_NAME }}
          app-name: ${{ env.APP_NAME }}
          use-staging-deployment: ${{ env.ENV_DEV }}
          package: ${{ env.ASC_PACKAGE_PATH }}/**/*.jar
